base:
  model_class: qwen3_0_6b
  checkpoint: /Users/amk/Desktop/Aaryan/deer/Hackathon/arm_s2s/models/llm/qwen3_converted.bin
  params: /Users/amk/Desktop/Aaryan/deer/Hackathon/arm_s2s/models/llm/0_6b_config.json

model:
  use_sdpa_with_kv_cache: true
  use_kv_cache: true
  dtype_override: fp32

export:
  max_seq_length: 128
  max_context_length: 512
  output_name: /Users/amk/Desktop/Aaryan/deer/Hackathon/arm_s2s/models/llm/qwen3_0.6B.pte

quantization:
  qmode: "8da4w"
  group_size: 128
  embedding_quantize: "4,32"

backend:
  xnnpack:
    enabled: true
    extended_ops: true
